version: '3.1'

services:
  app:
    image: java:17
    build: .
    ports:
      - "8080:8080"
      - "5005:5005"
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
